fail_on_severity: moderate
fail_on_scopes: ['runtime']
vulnerability_check: true
license_check: true
base_ref: 'main'
head_ref: 'HEAD'
allow_licenses:
  - 'MIT'
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'ISC'
  - 'GPL-2.0'
  - 'GPL-3.0'
  - 'LGPL-2.1'
  - 'LGPL-3.0'
deny_licenses:
  - 'MS-PL'
  - 'WTFPL'
  - 'JSON'