{{- if .Values.isaSuperapp.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "isa-superapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "isa-superapp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "isa-superapp.fullname" . }}
  minReplicas: {{ .Values.isaSuperapp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.isaSuperapp.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.isaSuperapp.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.isaSuperapp.autoscaling.targetMemoryUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
        selectPolicy: Max
      - type: Pods
        value: 2
        periodSeconds: 60
        selectPolicy: Max
      selectPolicy: Max
{{- end }}