apiVersion: v1
kind: ServiceAccount
metadata:
  name: isa-superapp
  namespace: isa-superapp
  labels:
    app.kubernetes.io/name: isa-superapp
    app.kubernetes.io/component: serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: isa-frontend
  namespace: isa-superapp
  labels:
    app.kubernetes.io/name: isa-frontend
    app.kubernetes.io/component: serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: isa-monitoring
  namespace: isa-monitoring
  labels:
    app.kubernetes.io/name: isa-monitoring
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isa-superapp-role
  labels:
    app.kubernetes.io/name: isa-superapp
    app.kubernetes.io/component: clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: isa-superapp-binding
  labels:
    app.kubernetes.io/name: isa-superapp
    app.kubernetes.io/component: clusterrolebinding
subjects:
- kind: ServiceAccount
  name: isa-superapp
  namespace: isa-superapp
roleRef:
  kind: ClusterRole
  name: isa-superapp-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isa-monitoring-role
  labels:
    app.kubernetes.io/name: isa-monitoring
    app.kubernetes.io/component: clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: isa-monitoring-binding
  labels:
    app.kubernetes.io/name: isa-monitoring
    app.kubernetes.io/component: clusterrolebinding
subjects:
- kind: ServiceAccount
  name: isa-monitoring
  namespace: isa-monitoring
roleRef:
  kind: ClusterRole
  name: isa-monitoring-role
  apiGroup: rbac.authorization.k8s.io