apiVersion: v1
kind: Secret
metadata:
  name: isa-superapp-secrets
  namespace: isa-superapp
  labels:
    app.kubernetes.io/name: isa-superapp
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Placeholder values - replace with actual base64 encoded secrets
  DB_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  REDIS_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  NEO4J_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  OPENAI_API_KEY: cGxhY2Vob2xkZXI=  # placeholder
  ANTHROPIC_API_KEY: cGxhY2Vob2xkZXI=  # placeholder
  GEMINI_API_KEY: cGxhY2Vob2xkZXI=  # placeholder
  JWT_SECRET: cGxhY2Vob2xkZXI=  # placeholder
  SECRET_KEY: cGxhY2Vob2xkZXI=  # placeholder
  AWS_ACCESS_KEY_ID: cGxhY2Vob2xkZXI=  # placeholder
  AWS_SECRET_ACCESS_KEY: cGxhY2Vob2xkZXI=  # placeholder
  SMTP_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  GRAFANA_ADMIN_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
---
apiVersion: v1
kind: Secret
metadata:
  name: isa-database-secrets
  namespace: isa-database
  labels:
    app.kubernetes.io/name: isa-database
    app.kubernetes.io/component: secret
type: Opaque
data:
  # PostgreSQL credentials
  POSTGRES_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  POSTGRES_USER: aXNhX3VzZXI=  # isa_user
  POSTGRES_DB: aXNhX3N1cGVyYXBw  # isa_superapp
  # Neo4j credentials
  NEO4J_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  # OpenEPCIS credentials
  OPENEPCIS_DB_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
---
apiVersion: v1
kind: Secret
metadata:
  name: isa-monitoring-secrets
  namespace: isa-monitoring
  labels:
    app.kubernetes.io/name: isa-monitoring
    app.kubernetes.io/component: secret
type: Opaque
data:
  # SMTP credentials for alerts
  SMTP_USER: cGxhY2Vob2xkZXI=  # placeholder
  SMTP_PASSWORD: cGxhY2Vob2xkZXI=  # placeholder
  # Slack webhook for notifications
  SLACK_WEBHOOK_URL: cGxhY2Vob2xkZXI=  # placeholder
---
# AWS Secrets Manager integration (if using external secrets operator)
apiVersion: v1
kind: Secret
metadata:
  name: aws-secretsmanager
  namespace: isa-superapp
  labels:
    app.kubernetes.io/name: isa-superapp
    app.kubernetes.io/component: aws-secrets
type: Opaque
data:
  # AWS region for secrets manager
  AWS_REGION: dXMtZWFzdC0x  # us-east-1
  # Secrets Manager ARN
  SECRETS_MANAGER_ARN: cGxhY2Vob2xkZXI=  # placeholder