# Production values for ISA SuperApp Helm chart
# This file contains production-specific configurations

# Global configuration
global:
  imageRegistry: "123456789012.dkr.ecr.us-east-1.amazonaws.com"
  imagePullSecrets:
    - name: ecr-registry-secret
  storageClass: "gp3"
  environment: "production"

# ISA SuperApp configuration
isaSuperapp:
  enabled: true
  replicaCount: 5
  image:
    repository: "isa-superapp"
    tag: ""  # Will be set by CI/CD pipeline
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  autoscaling:
    enabled: true
    minReplicas: 5
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  nodeSelector:
    environment: production
    workload: application
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - isa-superapp
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        preference:
          matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - c5.large
            - c5.xlarge
            - c6i.large
            - c6i.xlarge
            - m5.large
            - m5.xlarge

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: "isa-frontend"
    tag: ""  # Will be set by CI/CD pipeline
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 70

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: ""  # Set via external secret
    username: "isa_user"
    password: ""  # Set via external secret
    database: "isa_superapp"
  architecture: "standalone"
  primary:
    persistence:
      enabled: true
      size: 100Gi
      storageClass: "gp3"
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    nodeSelector:
      environment: production
      workload: database

# Redis configuration
redis:
  enabled: true
  auth:
    password: ""  # Set via external secret
  architecture: "standalone"
  master:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "gp3"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    nodeSelector:
      environment: production
      workload: cache

# Neo4j configuration
neo4j:
  enabled: true
  name: "isa-neo4j"
  acceptLicenseAgreement: "yes"
  neo4jPassword: ""  # Set via external secret
  neo4jEdition: "enterprise"
  volumes:
    data:
      mode: "defaultStorageClass"
      defaultStorageClass:
        requests:
          storage: 200Gi
        storageClassName: "gp3"
    logs:
      mode: "defaultStorageClass"
      defaultStorageClass:
        requests:
          storage: 50Gi
        storageClassName: "gp3"
  resources:
    requests:
      cpu: 2000m
      memory: 8Gi
    limits:
      cpu: 4000m
      memory: 16Gi
  nodeSelector:
    environment: production
    workload: graph-database

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    server:
      persistentVolume:
        enabled: true
        size: 100Gi
        storageClass: "gp3"
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi
  grafana:
    enabled: true
    adminPassword: ""  # Set via external secret
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "gp3"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

# Ingress configuration
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:123456789012:certificate/production-isa-superapp"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:us-east-1:123456789012:regional/webacl/production-isa-waf"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header Referrer-Policy "no-referrer-when-downgrade" always;
      add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
  hosts:
    - host: api.isa-superapp.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: isa-superapp
              port:
                number: 8000
    - host: app.isa-superapp.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: isa-frontend
              port:
                number: 80
  tls:
    - secretName: isa-tls-secret
      hosts:
        - api.isa-superapp.com
        - app.isa-superapp.com

# Security configuration
security:
  networkPolicy:
    enabled: true
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL

# AWS configuration
aws:
  region: "us-east-1"
  accountId: "123456789012"
  eks:
    clusterName: "isa-production-cluster"
  iam:
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/isa-superapp-production-sa-role"

# External secrets configuration
externalSecrets:
  enabled: true
  secretStore:
    name: "aws-secretsmanager"
    region: "us-east-1"
  secrets:
    - name: "isa-superapp-secrets"
      secretName: "isa-superapp-secrets"
      refreshInterval: "15s"
      secretStoreRef:
        name: "aws-secretsmanager"
        kind: "SecretStore"
      target:
        name: "isa-superapp-secrets"
        creationPolicy: "Owner"
      dataFrom:
        - "isa-superapp/production/*"