apiVersion: apps/v1
kind: Deployment
metadata:
  name: isa-superapp
  namespace: isa-superapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: isa-superapp
      app.kubernetes.io/instance: production
  template:
    spec:
      containers:
      - name: isa-superapp
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: DEBUG
          value: "true"
        - name: ENABLE_PROFILING
          value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3