
substitutions:
  _FIREBASE_TOKEN: $FIREBASE_TOKEN

steps:
  # Step 1: Checkout code
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://source.developers.google.com/p/$PROJECT_ID/r/default']

  # Step 2: Setup Node for functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'

  # Step 3: Lint and test
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: 'functions'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    dir: 'functions'

  # Step 4: Run schema validation script
  - name: 'python'
    entrypoint: 'python3'
    args: ['scripts/validate_schema_links.py']

  # Step 5: Conditional Deploy (Staging or Production)
  - name: 'gcr.io/firebase-ci/firebase'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]; then
          firebase deploy --project=${_PROD_PROJECT_ID} --token=${_FIREBASE_TOKEN}
        else
          firebase deploy --project=${_STAGE_PROJECT_ID} --token=${_FIREBASE_TOKEN}
