apiVersion: apps/v1
kind: Deployment
metadata:
  name: isa-superapp
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: isa-superapp
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi