apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isa-superapp-data
  labels:
    app: isa-superapp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard