apiVersion: v1
kind: Secret
metadata:
  name: isa-superapp-secrets
  labels:
    app.kubernetes.io/name: isa-superapp
    app.kubernetes.io/component: backend
type: Opaque
data:
  # Base64 encoded placeholder values - replace with actual secrets
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9kYg==
  redis-url: cmVkaXM6Ly9yZWRpczozNjM3OS8w
  jwt-secret: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  api-key: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=