name: Auto-merge PRs (label-driven)

on:
  pull_request:
    types: [labeled, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
