name: Determinism Matrix

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # daily at 06:00 UTC

jobs:
  snapshot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run determinism check (advisory)
        continue-on-error: true
        run: |
          # Use an existing deterministic test (splitter produces identical chunks)
          pytest -q infra/rag/tests/test_splitter.py || true
