name: Research Seed (Nightly)

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml
      - name: Index W3C TR fixture into VectorIndex
        run: |
          python - << 'PY'
          from scripts.research.index_docs import index_tr_fixture
          n = index_tr_fixture('scripts/research/tests/fixtures/w3c_tr_index.json','research_index.json')
          print('indexed docs:', n)
          PY
      - name: Index Federal Register fixture into VectorIndex
        run: |
          python - << 'PY'
          from scripts.research.index_docs import index_fr_fixture
          n = index_fr_fixture('scripts/research/tests/fixtures/federal_register_sample.json','research_index_fr.json')
          print('indexed FR docs:', n)
          PY
      - name: Eval RAG (offline)
        run: |
          python scripts/research/eval_rag.py research_index.json > eval_tr.json
          python scripts/research/eval_rag.py research_index_fr.json > eval_fr.json
      - name: Upload research index
        uses: actions/upload-artifact@v4
        with:
          name: research_indexes_and_eval
          path: |
            research_index.json
            research_index_fr.json
            eval_tr.json
            eval_fr.json
